version: "3"

services:
  backend_dev:
    container_name: backend_dev
    image: task-management-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  backend_prod:
    container_name: backend_prod
    image: task-management-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}